name: deploy diary
on:
  push:
    branches:
      - '**'
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Deploy
        run: curl ${{ secrets.DEPLOY_HOOK }}
